export enum Ambiente {
  PRODUCAO = 1,
  HOMOLOGACAO = 2
}

export enum TipoEmitente {
  PRESTADOR = 1,
  TOMADOR = 2,
  INTERMEDIARIO = 3
}

export enum IndicadorCpfCnpj {
  CPF = 1,
  CNPJ = 2
}

export enum IndicadorInscricaoEstadual {
  CONTRIBUINTE_ICMS = 1,
  CONTRIBUINTE_ISENTO = 2,
  NAO_CONTRIBUINTE = 9
}

export enum TipoTributacao {
  TRIBUTAVEL_DENTRO_MUNICIPIO = 1,
  TRIBUTAVEL_FORA_MUNICIPIO = 2,
  ISENCAO = 3,
  IMUNIDADE = 4,
  EXIGIBILIDADE_SUSPENSA_DECISAO_JUDICIAL = 5,
  EXIGIBILIDADE_SUSPENSA_PROCESSO_ADMINISTRATIVO = 6,
  NAO_TRIBUTAVEL = 7,
  EXPORTACAO = 8
}

export enum IndicadorExigibilidadeIss {
  EXIGIVEL = 1,
  NAO_INCIDENCIA = 2,
  ISENCAO = 3,
  EXPORTACAO = 4,
  IMUNIDADE = 5,
  EXIGIBILIDADE_SUSPENSA_DECISAO_JUDICIAL = 6,
  EXIGIBILIDADE_SUSPENSA_PROCESSO_ADMINISTRATIVO = 7
}

export enum IndicadorIncentivoFiscal {
  NAO = 1,
  SIM = 2
}

export enum RegimeEspecialTributacao {
  MICROEMPRESA_MUNICIPAL = 1,
  ESTIMATIVA = 2,
  SOCIEDADE_PROFISSIONAIS = 3,
  COOPERATIVA = 4,
  MICROEMPRESARIO_INDIVIDUAL = 5,
  MICROEMPRESA_PEQUENO_PORTE = 6
}

export enum IndicadorOperacao {
  SEM_DEDUCAO = 1,
  COM_DEDUCAO_MATERIAIS = 2,
  IMUNE_ISENTA_ISSQN = 3,
  DEVOLUCAO_SIMB_MERC = 4
}

export enum ClassificacaoTributaria {
  TRIBUTAVEL_FIXO = 1,
  TRIBUTAVEL_VARIAVEL = 2,
  TRIBUTAVEL_SOCIEDADE_PROFISSIONAIS = 3,
  IMUNE = 4,
  ISENTA = 5,
  EXPORTACAO = 6
}

export enum IndicadorTipoDeducao {
  DESPESAS_MATERIAIS = 1,
  DESPESAS_SUBEMPREITADA = 2,
  DESPESAS_ALIMENTACAO_TRANSPORTE = 3,
  OUTRAS_DEDUCOES = 99
}

export enum IndicadorDocumentoDeducao {
  NF_MODELO_1_1A = 1,
  NF_AVULSA = 2,
  NF_PRODUTOR = 4,
  NF_ENERGIA_ELETRICA = 6,
  NOTA_SERVICO_TRANSPORTE = 7,
  CONHECIMENTO_TRANSPORTE_RODOVIARIO = 8,
  CONHECIMENTO_TRANSPORTE_AQUAVIARIO = 9,
  CONHECIMENTO_AEREO = 10,
  CONHECIMENTO_TRANSPORTE_FERROVIARIO = 11,
  BILHETE_PASSAGEM_RODOVIARIO = 13,
  BILHETE_PASSAGEM_AQUAVIARIO = 14,
  BILHETE_PASSAGEM_AEREO = 15,
  BILHETE_PASSAGEM_FERROVIARIO = 16,
  NF_SERVICOS = 21,
  NF_SERVICOS_COMUNICACAO = 22,
  NFSE = 99
}

export enum IndicadorPaisExterior {
  PRESTACAO_EXTERIOR = 1,
  AQUISICAO_EXTERIOR = 2
}

export enum IdentificadorTipoDeducao {
  DEDUCAO = 1,
  REDUCAO = 2
}